/**
 * Builder Module — `source_progress` card application.
 *
 * Accepts proposed values generated by source enrichment and copies only the
 * grounded fields with canonical owned homes into builderState.
 */

import {
  patchBuilderState,
  applyConfirmation,
  type BuilderState,
  type DeepPartial,
  type SourceProposal,
} from '../../builder-state'
import type { SourceProgressPayload } from '../../card-submit.schemas'
import { sanitizeStringList, type CardApplication } from '../apply-card-submit'

/**
 * Resolve the values to commit when the user ACCEPTS the source proposal:
 * start from the stored `proposed` synthesis, let `edited` override per field,
 * then re-sanitize EVERY value server-side (never trust the body). Returns a
 * clean `SourceProposal` carrying only grounded, non-empty fields.
 */
function resolveAcceptedProposal(
  proposed: SourceProposal | undefined,
  edited: SourceProgressPayload['edited'],
): SourceProposal {
  const base = proposed ?? {}
  const out: SourceProposal = {}

  // Scalars: edited wins; fall back to the stored proposal. Trim + drop empties.
  const businessName = (edited?.businessName ?? base.businessName)?.trim()
  if (businessName) out.businessName = businessName

  const audience = (edited?.audience ?? base.audience)?.trim()
  if (audience) out.audience = audience

  const tone = (edited?.tone ?? base.tone)?.trim()
  if (tone) out.tone = tone

  // Onda E — identidade do negócio (endereço completo + descrição 1-2 frases).
  const address = (edited?.address ?? base.address)?.trim()
  if (address) out.address = address

  const description = (edited?.description ?? base.description)?.trim()
  if (description) out.description = description

  // Lists: edited replaces the proposal wholesale when supplied. Trim + dedupe.
  const services = sanitizeStringList(edited?.services ?? base.services ?? [])
  if (services.length > 0) out.services = services

  const differentiators = sanitizeStringList(
    edited?.differentiators ?? base.differentiators ?? [],
  )
  if (differentiators.length > 0) out.differentiators = differentiators

  return out
}

/**
 * source_progress — the "cole seu site/IG" acceptance gate. The async
 * `quayer:source-enrich` job has already written PROPOSED values into
 * `state.sourceIngestion.proposed`; here the user ACCEPTS them, so we copy the
 * (optionally edited) proposal into the OWNED builderState fields and flip the
 * `source` sentinel.
 *
 * Owned-field mapping (only fields with a canonical home are committed):
 *   - businessName    → project.name
 *   - audience        → project.objective  (ONLY when objective is still empty —
 *                       FR-02: never overwrite what the user already typed)
 *   - tone            → persona.tone
 *   - services        → services.offered    (UNIONed with already-confirmed list)
 *   - address         → identity.address     (Onda E)
 *   - description     → identity.description (Onda E)
 *   - differentiators → kept in `proposed` + RAG (no owned field today; never
 *                       force-fit into a mismatched slot — see the report note).
 *
 * Anti-hallucination: this is the ONLY place `confirmations.source` flips. The
 * synthesis job never touches owned fields nor the sentinel.
 */
export function applySourceProgress(
  state: BuilderState,
  edited: SourceProgressPayload['edited'],
): CardApplication {
  const accepted = resolveAcceptedProposal(state.sourceIngestion.proposed, edited)

  // Build the patch ONLY from fields that resolved to a value, so accepting a
  // sparse proposal never clobbers unrelated owned values with empties.
  const patch: DeepPartial<BuilderState> = {}

  // FR-02 (jornada-builder-v2) — `audience` é só um PROXY de objetivo: preenche
  // `project.objective` apenas quando ele ainda está vazio. Um objetivo que o
  // usuário já informou em texto livre NUNCA é sobrescrito pelo aceite da fonte.
  const objectiveAlreadySet =
    typeof state.project.objective === 'string' &&
    state.project.objective.trim().length > 0
  const applyAudience = Boolean(accepted.audience) && !objectiveAlreadySet

  if (accepted.businessName || applyAudience) {
    patch.project = {
      ...(accepted.businessName ? { name: accepted.businessName } : {}),
      ...(applyAudience && accepted.audience
        ? { objective: accepted.audience }
        : {}),
    }
  }
  if (accepted.tone) {
    patch.persona = { tone: accepted.tone }
  }
  if (accepted.address || accepted.description) {
    // Onda E — endereço + descrição do negócio têm um lar canônico próprio.
    patch.identity = {
      ...(accepted.address ? { address: accepted.address } : {}),
      ...(accepted.description ? { description: accepted.description } : {}),
    }
  }
  if (accepted.services && accepted.services.length > 0) {
    // Union with the already-present offered list (the user may have confirmed
    // services earlier) so accepting the source never DROPS prior choices.
    patch.services = {
      offered: sanitizeStringList([
        ...state.services.offered,
        ...accepted.services,
      ]),
    }
  }
  // `differentiators` has no owned field today; it stays in `proposed` (and in
  // the RAG collection) rather than being written to a mismatched slot.

  const next = applyConfirmation(patchBuilderState(state, patch), 'source')

  const bits: string[] = []
  if (accepted.businessName) bits.push(`nome "${accepted.businessName}"`)
  if (accepted.services && accepted.services.length > 0) {
    const noun = accepted.services.length === 1 ? 'serviço' : 'serviços'
    bits.push(`${accepted.services.length} ${noun}`)
  }
  if (applyAudience) bits.push('público-alvo')
  if (accepted.tone) bits.push(`tom "${accepted.tone}"`)
  if (accepted.address) bits.push(`endereço "${accepted.address}"`)
  if (accepted.description) bits.push('descrição do negócio')
  const summary = bits.length > 0 ? bits.join(', ') : 'as informações da fonte'
  return {
    next,
    cardInstruction:
      `O usuário ACEITOU os dados extraídos do site/Instagram via card (${summary}). ` +
      'Esses valores agora fazem parte do contexto do agente (e o conteúdo da fonte está na base de conhecimento). ' +
      'Use-os ao montar o agente e siga para o próximo passo da jornada. Não reabra o card de fontes.',
  }
}
