 
/* prettier-ignore */

/**
 * Generated by @igniter-js/cli
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY
 *
 * This file was automatically generated from your Igniter router.
 * Any changes made to this file will be overwritten when the CLI regenerates it.
 *
 * To modify the client API, update your controller files instead.
 *
 * Generated: 2026-06-06T18:11:00.650Z
 */

// Generated by @igniter-js/cli - DO NOT EDIT

export const AppRouterSchema = {
  "controllers": {
    "auth": {
      "name": "auth",
      "path": "/auth",
      "description": "Authentication and authorization (aggregated from 9 subdomain controllers)",
      "actions": {
        "refresh": {
          "name": "refresh",
          "path": "/refresh",
          "method": "POST",
          "description": "Refresh access token"
        },
        "logout": {
          "name": "logout",
          "path": "/logout",
          "method": "POST",
          "description": "Logout user",
          "bodySchema": {
            "type": "object",
            "properties": {
              "refreshToken": {
                "type": "string"
              },
              "everywhere": {
                "type": "boolean",
                "default": false
              }
            },
            "additionalProperties": false
          }
        },
        "csrf": {
          "name": "csrf",
          "path": "/csrf",
          "method": "GET",
          "description": "Generate a new CSRF token and set it as a cookie"
        },
        "switchOrganization": {
          "name": "switchOrganization",
          "path": "/switch-organization",
          "method": "POST",
          "description": "Switch current organization",
          "bodySchema": {
            "type": "object",
            "properties": {
              "organizationId": {
                "type": "string",
                "format": "uuid"
              }
            },
            "required": [
              "organizationId"
            ],
            "additionalProperties": false
          }
        },
        "me": {
          "name": "me",
          "path": "/me",
          "method": "GET",
          "description": "Get authenticated user data"
        },
        "updateMe": {
          "name": "updateMe",
          "path": "/me",
          "method": "PATCH",
          "description": "Update authenticated user profile fields",
          "bodySchema": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "minLength": 1,
                "maxLength": 120
              },
              "language": {
                "type": "string",
                "minLength": 2,
                "maxLength": 10
              },
              "timezone": {
                "type": "string",
                "minLength": 1,
                "maxLength": 64
              }
            },
            "additionalProperties": false
          }
        },
        "uploadAvatar": {
          "name": "uploadAvatar",
          "path": "/me/avatar",
          "method": "POST",
          "description": "Upload a new avatar for the authenticated user",
          "bodySchema": {
            "type": "object",
            "properties": {
              "fileBase64": {
                "type": "string",
                "minLength": 1
              },
              "fileName": {
                "type": "string",
                "minLength": 1
              },
              "mimeType": {
                "type": "string",
                "pattern": "^image\\/(jpeg|png|webp)$"
              }
            },
            "required": [
              "fileBase64",
              "fileName",
              "mimeType"
            ],
            "additionalProperties": false
          }
        },
        "getOtpPreferences": {
          "name": "getOtpPreferences",
          "path": "/me/otp-preferences",
          "method": "GET",
          "description": "Get user OTP method preferences"
        },
        "updateOtpPreferences": {
          "name": "updateOtpPreferences",
          "path": "/me/otp-preferences",
          "method": "PATCH",
          "description": "Enable or disable OTP login methods (requires active 2FA)",
          "bodySchema": {
            "type": "object",
            "properties": {
              "otpEmailDisabled": {
                "type": "boolean"
              },
              "otpPhoneDisabled": {
                "type": "boolean"
              }
            },
            "additionalProperties": false
          }
        },
        "listLinkedAccounts": {
          "name": "listLinkedAccounts",
          "path": "/me/linked-accounts",
          "method": "GET",
          "description": "List external identity providers linked to the authenticated user"
        },
        "unlinkAccount": {
          "name": "unlinkAccount",
          "path": "/me/linked-accounts/:provider",
          "method": "DELETE",
          "description": "Remove an external identity provider from the authenticated user"
        },
        "listUsers": {
          "name": "listUsers",
          "path": "/users",
          "method": "GET",
          "description": "List all users (admin only)"
        },
        "verifyEmail": {
          "name": "verifyEmail",
          "path": "/verify-email",
          "method": "POST",
          "description": "Verify email with code",
          "bodySchema": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email"
              },
              "code": {
                "type": "string",
                "minLength": 6,
                "maxLength": 6
              }
            },
            "required": [
              "email",
              "code"
            ],
            "additionalProperties": false
          }
        },
        "signupOTP": {
          "name": "signupOTP",
          "path": "/signup-otp",
          "method": "POST",
          "description": "Request signup code via email",
          "bodySchema": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "minLength": 2
              },
              "email": {
                "type": "string",
                "format": "email"
              }
            },
            "required": [
              "name",
              "email"
            ],
            "additionalProperties": false
          }
        },
        "verifySignupOTP": {
          "name": "verifySignupOTP",
          "path": "/verify-signup-otp",
          "method": "POST",
          "description": "Verify signup OTP and create user",
          "bodySchema": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email"
              },
              "code": {
                "type": "string",
                "minLength": 6,
                "maxLength": 6
              }
            },
            "required": [
              "email",
              "code"
            ],
            "additionalProperties": false
          }
        },
        "loginOTP": {
          "name": "loginOTP",
          "path": "/login-otp",
          "method": "POST",
          "description": "Request passwordless login code via email",
          "bodySchema": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email"
              },
              "rememberMe": {
                "type": "boolean",
                "default": false
              }
            },
            "required": [
              "email"
            ],
            "additionalProperties": false
          }
        },
        "verifyLoginOTP": {
          "name": "verifyLoginOTP",
          "path": "/verify-login-otp",
          "method": "POST",
          "description": "Verify passwordless OTP code",
          "bodySchema": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email"
              },
              "code": {
                "type": "string",
                "minLength": 6,
                "maxLength": 6
              },
              "rememberMe": {
                "type": "boolean",
                "default": false
              }
            },
            "required": [
              "email",
              "code"
            ],
            "additionalProperties": false
          }
        },
        "verifyMagicLink": {
          "name": "verifyMagicLink",
          "path": "/verify-magic-link",
          "method": "POST",
          "description": "Verify magic link token (login or signup)",
          "bodySchema": {
            "type": "object",
            "properties": {
              "token": {
                "type": "string"
              }
            },
            "required": [
              "token"
            ],
            "additionalProperties": false
          }
        },
        "checkMagicLinkStatus": {
          "name": "checkMagicLinkStatus",
          "path": "/check-magic-link-status",
          "method": "POST",
          "description": "Poll to check if magic link was verified (for cross-tab login)",
          "bodySchema": {
            "type": "object",
            "properties": {
              "sessionId": {
                "type": "string",
                "format": "uuid"
              }
            },
            "required": [
              "sessionId"
            ],
            "additionalProperties": false
          }
        },
        "googleAuth": {
          "name": "googleAuth",
          "path": "/google",
          "method": "GET",
          "description": "Initiate Google OAuth flow"
        },
        "googleCallback": {
          "name": "googleCallback",
          "path": "/google/callback",
          "method": "POST",
          "description": "Process Google OAuth callback",
          "bodySchema": {
            "type": "object",
            "properties": {
              "code": {
                "type": "string"
              },
              "state": {
                "type": "string",
                "minLength": 32,
                "maxLength": 128
              }
            },
            "required": [
              "code",
              "state"
            ],
            "additionalProperties": false
          }
        },
        "passkeyRegisterOptions": {
          "name": "passkeyRegisterOptions",
          "path": "/passkey/register/options",
          "method": "POST"
        },
        "passkeyRegisterVerify": {
          "name": "passkeyRegisterVerify",
          "path": "/passkey/register/verify",
          "method": "POST",
          "bodySchema": {
            "type": "object",
            "properties": {
              "response": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                  "rawId": {
                    "type": "string"
                  },
                  "response": {
                    "type": "object",
                    "properties": {
                      "clientDataJSON": {
                        "type": "string"
                      },
                      "attestationObject": {
                        "type": "string"
                      },
                      "transports": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      }
                    },
                    "required": [
                      "clientDataJSON",
                      "attestationObject"
                    ],
                    "additionalProperties": true
                  },
                  "type": {
                    "type": "string",
                    "enum": [
                      "public-key"
                    ]
                  },
                  "clientExtensionResults": {
                    "type": "object",
                    "additionalProperties": {}
                  },
                  "authenticatorAttachment": {
                    "type": "string"
                  }
                },
                "required": [
                  "id",
                  "rawId",
                  "response",
                  "type"
                ],
                "additionalProperties": true
              },
              "name": {
                "type": "string",
                "default": "Minha Passkey"
              }
            },
            "required": [
              "response"
            ],
            "additionalProperties": false
          }
        },
        "passkeyList": {
          "name": "passkeyList",
          "path": "/passkey/list",
          "method": "GET"
        },
        "passkeyDelete": {
          "name": "passkeyDelete",
          "path": "/passkey/:passkeyId",
          "method": "DELETE"
        },
        "passkeyLoginOptions": {
          "name": "passkeyLoginOptions",
          "path": "/passkey/login/options",
          "method": "POST",
          "bodySchema": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email"
              }
            },
            "required": [
              "email"
            ],
            "additionalProperties": false
          }
        },
        "passkeyLoginVerify": {
          "name": "passkeyLoginVerify",
          "path": "/passkey/login/verify",
          "method": "POST",
          "bodySchema": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email"
              },
              "response": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                  "rawId": {
                    "type": "string"
                  },
                  "response": {
                    "type": "object",
                    "properties": {
                      "clientDataJSON": {
                        "type": "string"
                      },
                      "authenticatorData": {
                        "type": "string"
                      },
                      "signature": {
                        "type": "string"
                      },
                      "userHandle": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "clientDataJSON",
                      "authenticatorData",
                      "signature"
                    ],
                    "additionalProperties": true
                  },
                  "type": {
                    "type": "string",
                    "enum": [
                      "public-key"
                    ]
                  },
                  "clientExtensionResults": {
                    "type": "object",
                    "additionalProperties": {}
                  },
                  "authenticatorAttachment": {
                    "type": "string"
                  }
                },
                "required": [
                  "id",
                  "rawId",
                  "response",
                  "type"
                ],
                "additionalProperties": true
              }
            },
            "required": [
              "email",
              "response"
            ],
            "additionalProperties": false
          }
        },
        "passkeyConditionalChallenge": {
          "name": "passkeyConditionalChallenge",
          "path": "/passkey/login/challenge",
          "method": "POST"
        },
        "passkeyConditionalVerify": {
          "name": "passkeyConditionalVerify",
          "path": "/passkey/login/verify-conditional",
          "method": "POST",
          "bodySchema": {
            "type": "object",
            "properties": {
              "response": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                  "rawId": {
                    "type": "string"
                  },
                  "response": {
                    "type": "object",
                    "properties": {
                      "clientDataJSON": {
                        "type": "string"
                      },
                      "authenticatorData": {
                        "type": "string"
                      },
                      "signature": {
                        "type": "string"
                      },
                      "userHandle": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "clientDataJSON",
                      "authenticatorData",
                      "signature"
                    ],
                    "additionalProperties": true
                  },
                  "type": {
                    "type": "string",
                    "enum": [
                      "public-key"
                    ]
                  },
                  "clientExtensionResults": {
                    "type": "object",
                    "additionalProperties": {}
                  },
                  "authenticatorAttachment": {
                    "type": "string"
                  }
                },
                "required": [
                  "id",
                  "rawId",
                  "response",
                  "type"
                ],
                "additionalProperties": true
              },
              "challengeId": {
                "type": "string"
              }
            },
            "required": [
              "response",
              "challengeId"
            ],
            "additionalProperties": false
          }
        },
        "loginOTPPhone": {
          "name": "loginOTPPhone",
          "path": "/login-otp-phone",
          "method": "POST",
          "bodySchema": {
            "type": "object",
            "properties": {
              "phone": {
                "type": "string",
                "minLength": 8,
                "maxLength": 20
              }
            },
            "required": [
              "phone"
            ],
            "additionalProperties": false
          }
        },
        "verifyLoginOTPPhone": {
          "name": "verifyLoginOTPPhone",
          "path": "/verify-login-otp-phone",
          "method": "POST",
          "description": "Verify WhatsApp OTP code and issue session",
          "bodySchema": {
            "type": "object",
            "properties": {
              "phone": {
                "type": "string",
                "minLength": 8,
                "maxLength": 20
              },
              "code": {
                "type": "string",
                "minLength": 6,
                "maxLength": 6
              }
            },
            "required": [
              "phone",
              "code"
            ],
            "additionalProperties": false
          }
        },
        "totpSetup": {
          "name": "totpSetup",
          "path": "/totp/setup",
          "method": "POST",
          "description": "Generate TOTP secret and QR code, create a pending TotpDevice"
        },
        "totpVerify": {
          "name": "totpVerify",
          "path": "/totp/verify",
          "method": "POST",
          "description": "Verify TOTP code and activate the pending device",
          "bodySchema": {
            "type": "object",
            "properties": {
              "code": {
                "type": "string",
                "minLength": 6,
                "maxLength": 8
              },
              "deviceId": {
                "type": "string",
                "format": "uuid"
              },
              "name": {
                "type": "string",
                "minLength": 1,
                "maxLength": 100,
                "default": "Authenticator App"
              }
            },
            "required": [
              "code",
              "deviceId"
            ],
            "additionalProperties": false
          }
        },
        "totpDevices": {
          "name": "totpDevices",
          "path": "/totp/devices",
          "method": "GET",
          "description": "List active TOTP devices for the current user"
        },
        "totpDisableRequest": {
          "name": "totpDisableRequest",
          "path": "/totp/disable-request",
          "method": "POST",
          "description": "Send email verification code to initiate 2FA disablement",
          "bodySchema": {
            "type": "object",
            "properties": {
              "totpCode": {
                "type": "string",
                "minLength": 6,
                "maxLength": 8
              }
            },
            "required": [
              "totpCode"
            ],
            "additionalProperties": false
          }
        },
        "totpDisable": {
          "name": "totpDisable",
          "path": "/totp/disable",
          "method": "POST",
          "description": "Disable 2FA after verifying both email code and TOTP code",
          "bodySchema": {
            "type": "object",
            "properties": {
              "emailCode": {
                "type": "string",
                "minLength": 6,
                "maxLength": 8
              },
              "totpCode": {
                "type": "string",
                "minLength": 6,
                "maxLength": 8
              }
            },
            "required": [
              "emailCode",
              "totpCode"
            ],
            "additionalProperties": false
          }
        },
        "totpRegenerateCodes": {
          "name": "totpRegenerateCodes",
          "path": "/totp/regenerate-codes",
          "method": "POST",
          "description": "Regenerate recovery codes (requires valid TOTP code)",
          "bodySchema": {
            "type": "object",
            "properties": {
              "totpCode": {
                "type": "string",
                "minLength": 6,
                "maxLength": 8
              }
            },
            "required": [
              "totpCode"
            ],
            "additionalProperties": false
          }
        },
        "twoFactorLoginVerify": {
          "name": "twoFactorLoginVerify",
          "path": "/2fa/verify",
          "method": "POST",
          "description": "Complete login after first factor by verifying TOTP code or recovery code (H-5)",
          "bodySchema": {
            "type": "object",
            "properties": {
              "challengeId": {
                "type": "string",
                "minLength": 1
              },
              "code": {
                "type": "string",
                "minLength": 6,
                "maxLength": 10
              }
            },
            "required": [
              "challengeId",
              "code"
            ],
            "additionalProperties": false
          }
        }
      }
    },
    "builder": {
      "name": "builder",
      "path": "/builder",
      "description": "Builder IA — design-time para criação de agentes WhatsApp (não confundir com runtime em ai-agents)",
      "actions": {
        "listProjects": {
          "name": "listProjects",
          "path": "/projects",
          "method": "GET",
          "description": "Lista todos os Builder projects da organização atual, com filtros opcionais de tipo/status."
        },
        "getProject": {
          "name": "getProject",
          "path": "/projects/:id",
          "method": "GET",
          "description": "Retorna um BuilderProject pelo ID, incluindo a conversa 1:1 e o agente vinculado (quando existir)."
        },
        "createProject": {
          "name": "createProject",
          "path": "/projects/create",
          "method": "POST",
          "description": "Cria um BuilderProject (draft), sua conversa 1:1 e a primeira mensagem do usuário em uma única transação.",
          "bodySchema": {
            "type": "object",
            "properties": {
              "prompt": {
                "type": "string",
                "minLength": 3,
                "maxLength": 2000
              },
              "type": {
                "type": "string",
                "enum": [
                  "ai_agent"
                ]
              }
            },
            "required": [
              "prompt",
              "type"
            ],
            "additionalProperties": false
          }
        },
        "deleteProject": {
          "name": "deleteProject",
          "path": "/projects/:id",
          "method": "DELETE",
          "description": "Soft delete de um BuilderProject: marca status = archived e carimba archivedAt. Não remove o registro fisicamente."
        },
        "renameProject": {
          "name": "renameProject",
          "path": "/projects/:id/rename",
          "method": "PATCH",
          "description": "Renomeia um BuilderProject. Verifica posse por org.",
          "bodySchema": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "minLength": 1,
                "maxLength": 100
              }
            },
            "required": [
              "name"
            ],
            "additionalProperties": false
          }
        },
        "archiveProject": {
          "name": "archiveProject",
          "path": "/projects/:id/archive",
          "method": "PATCH",
          "description": "Arquiva um BuilderProject (status → archived). Verifica posse por org.",
          "bodySchema": {
            "type": "object",
            "properties": {},
            "additionalProperties": false
          }
        },
        "duplicateProject": {
          "name": "duplicateProject",
          "path": "/projects/:id/duplicate",
          "method": "POST",
          "description": "Clona um BuilderProject (+ AIAgentConfig + última BuilderPromptVersion). Não clona deployments/conversas/mensagens.",
          "bodySchema": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "minLength": 1,
                "maxLength": 100
              }
            },
            "additionalProperties": false
          }
        },
        "updateAgentSettings": {
          "name": "updateAgentSettings",
          "path": "/projects/:id/agent-settings",
          "method": "PATCH",
          "description": "Atualiza flags avançadas do agente: typing, idioma, mídia, buffer e áudio/TTS.",
          "bodySchema": {
            "type": "object",
            "additionalProperties": {}
          }
        },
        "updatePrompt": {
          "name": "updatePrompt",
          "path": "/projects/:id/prompt",
          "method": "PATCH",
          "description": "Auto-save do system prompt do AIAgentConfig vinculado ao projeto. Verifica posse por org. Retorna 404 se o projeto não existir ou não tiver agente vinculado.",
          "bodySchema": {
            "type": "object",
            "properties": {
              "systemPrompt": {
                "type": "string",
                "maxLength": 20000
              }
            },
            "required": [
              "systemPrompt"
            ],
            "additionalProperties": false
          }
        },
        "listVersions": {
          "name": "listVersions",
          "path": "/projects/:id/versions",
          "method": "GET",
          "description": "Retorna o histórico de versões do system prompt de um projeto Builder IA, ordenado por versionNumber DESC."
        },
        "rollbackPrompt": {
          "name": "rollbackPrompt",
          "path": "/projects/:id/prompt/rollback",
          "method": "POST",
          "description": "Cria uma nova BuilderPromptVersion com createdBy=rollback copiando o conteúdo de targetVersionId e atualiza o AIAgentConfig.systemPrompt. Não sobrescreve histórico.",
          "bodySchema": {
            "type": "object",
            "properties": {
              "targetVersionId": {
                "type": "string",
                "format": "uuid"
              }
            },
            "required": [
              "targetVersionId"
            ],
            "additionalProperties": false
          }
        },
        "getSidebar": {
          "name": "getSidebar",
          "path": "/sidebar",
          "method": "GET",
          "description": "Retorna os dados agregados consumidos pelo componente <BuilderSidebar> (projetos recentes + flag de super admin)."
        },
        "getMetrics": {
          "name": "getMetrics",
          "path": "/projects/:id/metrics",
          "method": "GET",
          "description": "Retorna métricas de uso das últimas 24h para um projeto Builder IA publicado (ChatSessions + Messages via AIAgentConfig). Requer aiAgentId vinculado."
        },
        "listProjectChannelOptions": {
          "name": "listProjectChannelOptions",
          "path": "/projects/:id/channel/options",
          "method": "GET",
          "description": "Lista canais WhatsApp existentes na organização para vincular ao projeto."
        },
        "getProjectChannel": {
          "name": "getProjectChannel",
          "path": "/projects/:id/channel",
          "method": "GET",
          "description": "Retorna o canal (Connection) ativo vinculado ao agente do projeto via AgentDeployment."
        },
        "attachChannel": {
          "name": "attachChannel",
          "path": "/projects/:id/channel",
          "method": "POST",
          "description": "Vincula um canal WhatsApp existente ao agente do projeto via AgentDeployment.",
          "bodySchema": {
            "type": "object",
            "properties": {
              "connectionId": {
                "type": "string",
                "format": "uuid"
              }
            },
            "required": [
              "connectionId"
            ],
            "additionalProperties": false
          }
        },
        "detachChannel": {
          "name": "detachChannel",
          "path": "/projects/:id/channel",
          "method": "DELETE",
          "description": "Remove o vínculo entre o canal ativo e o agente do projeto.",
          "bodySchema": {
            "anyOf": [
              {
                "not": {}
              },
              {
                "type": "object",
                "properties": {},
                "additionalProperties": false
              }
            ]
          }
        },
        "playgroundStream": {
          "name": "playgroundStream",
          "path": "/projects/:id/playground/stream",
          "method": "POST",
          "description": "Stateless SSE stream for testing an agent in the Playground tab. Does NOT persist any messages, tool calls, or metrics.",
          "bodySchema": {
            "type": "object",
            "properties": {
              "message": {
                "type": "string",
                "minLength": 1,
                "maxLength": 4000
              },
              "history": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "role": {
                      "type": "string",
                      "enum": [
                        "user",
                        "assistant"
                      ]
                    },
                    "content": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "role",
                    "content"
                  ],
                  "additionalProperties": false
                },
                "maxItems": 50,
                "default": []
              }
            },
            "required": [
              "message"
            ],
            "additionalProperties": false
          }
        },
        "sendMessage": {
          "name": "sendMessage",
          "path": "/projects/:id/chat/message",
          "method": "POST",
          "description": "Send a user message to the Builder meta-agent and stream the response via SSE (text-delta, tool-call, tool-result, finish, error).",
          "bodySchema": {
            "type": "object",
            "properties": {
              "content": {
                "type": "string",
                "minLength": 1,
                "maxLength": 10000
              },
              "skipUserPersist": {
                "type": "boolean"
              }
            },
            "required": [
              "content"
            ],
            "additionalProperties": false
          }
        },
        "listMessages": {
          "name": "listMessages",
          "path": "/projects/:id/chat/messages",
          "method": "GET",
          "description": "Paginated list of BuilderProjectMessage rows for a given project, newest-first."
        },
        "getReadiness": {
          "name": "getReadiness",
          "path": "/projects/:id/readiness",
          "method": "GET",
          "description": "Resolve the deterministic step-engine Readiness for a Builder project: next step, completeness, typed deploy blockers, and field ownership. Drives the UI progress view (single source of truth with the prompt banner)."
        },
        "compact": {
          "name": "compact",
          "path": "/projects/:id/chat/compact",
          "method": "POST",
          "description": "Manually trigger a context-budget compaction pass for this project conversation.",
          "bodySchema": {
            "anyOf": [
              {
                "not": {}
              },
              {
                "type": "object",
                "properties": {},
                "additionalProperties": false
              }
            ]
          }
        },
        "submitCard": {
          "name": "submitCard",
          "path": "/projects/:id/cards/:cardKey/submit",
          "method": "POST",
          "description": "Apply a card payload deterministically to the conversation builderState (flips the matching *_confirmed sentinel) and stream the agent ACK turn via SSE. Replaces the legacy approval-by-regex flow.",
          "bodySchema": {
            "anyOf": [
              {
                "type": "object",
                "properties": {
                  "cardKey": {
                    "type": "string",
                    "enum": [
                      "agent_approval"
                    ]
                  },
                  "action": {
                    "type": "string",
                    "enum": [
                      "confirm"
                    ]
                  }
                },
                "required": [
                  "cardKey",
                  "action"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "cardKey": {
                    "type": "string",
                    "enum": [
                      "tool_selection"
                    ]
                  },
                  "action": {
                    "type": "string",
                    "enum": [
                      "apply"
                    ]
                  },
                  "capabilityKeys": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "minLength": 1,
                      "maxLength": 120
                    },
                    "maxItems": 64,
                    "default": []
                  },
                  "toolKeys": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "minLength": 1,
                      "maxLength": 120
                    },
                    "maxItems": 64,
                    "default": []
                  }
                },
                "required": [
                  "cardKey",
                  "action"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "cardKey": {
                    "type": "string",
                    "enum": [
                      "channel"
                    ]
                  },
                  "action": {
                    "type": "string",
                    "enum": [
                      "select"
                    ]
                  },
                  "channelKey": {
                    "type": "string",
                    "enum": [
                      "cloudapi",
                      "uazapi",
                      "instagram"
                    ]
                  }
                },
                "required": [
                  "cardKey",
                  "action",
                  "channelKey"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "cardKey": {
                    "type": "string",
                    "enum": [
                      "agent_persona"
                    ]
                  },
                  "persona": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 120
                      },
                      "tone": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 120
                      },
                      "style": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 120
                      },
                      "greeting": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 2000
                      },
                      "speechMode": {
                        "type": "string",
                        "enum": [
                          "assistant",
                          "first_person",
                          "secretary"
                        ]
                      }
                    },
                    "additionalProperties": false,
                    "default": {}
                  }
                },
                "required": [
                  "cardKey"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "cardKey": {
                    "type": "string",
                    "enum": [
                      "services"
                    ]
                  },
                  "offered": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "minLength": 1
                    },
                    "default": []
                  },
                  "notOffered": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "minLength": 1
                    },
                    "default": []
                  }
                },
                "required": [
                  "cardKey"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "cardKey": {
                    "type": "string",
                    "enum": [
                      "business_hours"
                    ]
                  },
                  "preset": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 120
                  },
                  "schedule": {},
                  "timezone": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 120
                  }
                },
                "required": [
                  "cardKey"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "cardKey": {
                    "type": "string",
                    "enum": [
                      "pricing"
                    ]
                  },
                  "items": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string",
                          "minLength": 1,
                          "maxLength": 200
                        },
                        "priceCents": {
                          "type": "integer",
                          "minimum": 0
                        },
                        "category": {
                          "type": "string",
                          "minLength": 1,
                          "maxLength": 120
                        },
                        "priceMaxCents": {
                          "type": "integer",
                          "minimum": 0
                        },
                        "imageUrl": {
                          "type": "string",
                          "format": "uri",
                          "maxLength": 2000
                        }
                      },
                      "required": [
                        "name",
                        "priceCents"
                      ],
                      "additionalProperties": false
                    },
                    "default": []
                  },
                  "currency": {
                    "type": "string",
                    "minLength": 3,
                    "maxLength": 3,
                    "default": "BRL"
                  },
                  "disclosureStyle": {
                    "type": "string",
                    "enum": [
                      "exact",
                      "from",
                      "average",
                      "none"
                    ],
                    "default": "exact"
                  },
                  "minTicketCents": {
                    "type": "integer",
                    "minimum": 0
                  }
                },
                "required": [
                  "cardKey"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "cardKey": {
                    "type": "string",
                    "enum": [
                      "qualification_action"
                    ]
                  },
                  "action": {
                    "type": "string",
                    "enum": [
                      "notify_team",
                      "book_appointment",
                      "lead_only"
                    ]
                  }
                },
                "required": [
                  "cardKey",
                  "action"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "cardKey": {
                    "type": "string",
                    "enum": [
                      "qualification_steps"
                    ]
                  },
                  "steps": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "minLength": 1
                    },
                    "default": []
                  }
                },
                "required": [
                  "cardKey"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "cardKey": {
                    "type": "string",
                    "enum": [
                      "team_structure"
                    ]
                  },
                  "departmentName": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 200
                  },
                  "departmentType": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 120
                  },
                  "members": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "userId": {
                          "type": "string",
                          "minLength": 1
                        },
                        "name": {
                          "type": "string",
                          "minLength": 1,
                          "maxLength": 200
                        },
                        "whatsapp": {
                          "type": "string",
                          "minLength": 1,
                          "maxLength": 40
                        },
                        "position": {
                          "type": "integer",
                          "minimum": 0
                        }
                      },
                      "required": [
                        "position"
                      ],
                      "additionalProperties": false
                    },
                    "default": []
                  }
                },
                "required": [
                  "cardKey"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "cardKey": {
                    "type": "string",
                    "enum": [
                      "calendar_connect"
                    ]
                  },
                  "connectionId": {
                    "type": "string",
                    "minLength": 1
                  },
                  "status": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 120
                  }
                },
                "required": [
                  "cardKey"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "cardKey": {
                    "type": "string",
                    "enum": [
                      "activation_mode"
                    ]
                  },
                  "mode": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 120
                  },
                  "keywords": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "minLength": 1
                    },
                    "default": []
                  }
                },
                "required": [
                  "cardKey",
                  "mode"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "cardKey": {
                    "type": "string",
                    "enum": [
                      "preview_summary"
                    ]
                  }
                },
                "required": [
                  "cardKey"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "cardKey": {
                    "type": "string",
                    "enum": [
                      "quick_reply_chips"
                    ]
                  },
                  "value": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 2000
                  }
                },
                "required": [
                  "cardKey",
                  "value"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "cardKey": {
                    "type": "string",
                    "enum": [
                      "source_progress"
                    ]
                  },
                  "accept": {
                    "type": "boolean",
                    "enum": [
                      true
                    ]
                  },
                  "edited": {
                    "type": "object",
                    "properties": {
                      "businessName": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 200
                      },
                      "services": {
                        "type": "array",
                        "items": {
                          "type": "string",
                          "minLength": 1
                        }
                      },
                      "audience": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 2000
                      },
                      "differentiators": {
                        "type": "array",
                        "items": {
                          "type": "string",
                          "minLength": 1
                        }
                      },
                      "tone": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 120
                      }
                    },
                    "additionalProperties": false
                  }
                },
                "required": [
                  "cardKey",
                  "accept"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "cardKey": {
                    "type": "string",
                    "enum": [
                      "silenced_contacts"
                    ]
                  },
                  "contacts": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string",
                          "minLength": 1,
                          "maxLength": 120
                        },
                        "whatsapp": {
                          "type": "string",
                          "minLength": 1,
                          "maxLength": 40
                        }
                      },
                      "required": [
                        "whatsapp"
                      ],
                      "additionalProperties": false
                    },
                    "maxItems": 50,
                    "default": []
                  },
                  "acknowledged": {
                    "type": "boolean",
                    "enum": [
                      true
                    ]
                  }
                },
                "required": [
                  "cardKey",
                  "acknowledged"
                ],
                "additionalProperties": false
              }
            ]
          }
        },
        "parseSheet": {
          "name": "parseSheet",
          "path": "/projects/:id/sheet/parse",
          "method": "POST",
          "description": "Parse a PUBLIC Google Sheets URL (CSV gviz export, SSRF-safe allowlist docs.google.com/spreadsheets only) and return detected headers, a row preview (≤50), the full row count, a hasHeader flag, and per-column role suggestions (servico/preco/categoria) for the FE column mapper. STATELESS — no DB write; the org gate only authorizes the route.",
          "bodySchema": {
            "type": "object",
            "properties": {
              "sheetUrl": {
                "type": "string",
                "minLength": 1,
                "maxLength": 2000
              }
            },
            "required": [
              "sheetUrl"
            ],
            "additionalProperties": false
          }
        },
        "ingestSources": {
          "name": "ingestSources",
          "path": "/projects/:id/sources/ingest",
          "method": "POST",
          "description": "Create a KnowledgeSource (status=pending) per pasted site/Instagram ref, seed builderState.sourceIngestion.sources, and enqueue the async quayer:source-enrich job (extract→chunk→embed→pgvector + proposed-only synthesis). Enrichment never runs inline.",
          "bodySchema": {
            "type": "object",
            "properties": {
              "refs": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "value": {
                      "type": "string",
                      "format": "uri"
                    },
                    "type": {
                      "type": "string",
                      "enum": [
                        "url",
                        "instagram"
                      ]
                    }
                  },
                  "required": [
                    "value",
                    "type"
                  ],
                  "additionalProperties": false
                },
                "minItems": 1,
                "maxItems": 10
              }
            },
            "required": [
              "refs"
            ],
            "additionalProperties": false
          }
        },
        "sourcesStatus": {
          "name": "sourcesStatus",
          "path": "/projects/:id/sources/status",
          "method": "GET",
          "description": "Poll the status of a project's ingested sources: each KnowledgeSource ({id,source,type,status,chunkCount,error}) for the project collection plus the synthesized builderState.sourceIngestion.proposed (PROPOSED values awaiting Aceitar). Org-scoped."
        },
        "listSourceImages": {
          "name": "listSourceImages",
          "path": "/projects/:id/sources/images",
          "method": "GET",
          "description": "List the curation catalog of images extracted from a project's sources (KnowledgeImage rows of collection kb:projectId, deletedAt IS NULL), org-scoped. Each row's storageKey is signed ON-READ (BUCKETS.MEDIA) into imageUrl — fail-safe: a failed signature yields imageUrl=null for that image and never drops the list. storageKey is never exposed."
        },
        "patchSourceImage": {
          "name": "patchSourceImage",
          "path": "/sources/images/:imageId",
          "method": "PATCH",
          "description": "Curate a single extracted image (exactly ONE action per call): set caption, soft-delete (deleted:true), or confirm/unconfirm (confirmed). Org-scoped via the repository updateMany ({id, organizationId}); affected count 0 ⇒ 404 (not found / no access).",
          "bodySchema": {
            "type": "object",
            "properties": {
              "caption": {
                "type": "string",
                "maxLength": 2000
              },
              "deleted": {
                "type": "boolean",
                "enum": [
                  true
                ]
              },
              "confirmed": {
                "type": "boolean"
              }
            },
            "additionalProperties": false
          }
        },
        "bulkSourceImages": {
          "name": "bulkSourceImages",
          "path": "/projects/:id/sources/images/bulk",
          "method": "POST",
          "description": "Bulk-curate a project's extracted images, org-scoped: \"approve_all\" confirms every pending image (confirmedAt IS NULL, deletedAt IS NULL); \"delete_low_quality\" soft-deletes by a low-quality heuristic (missing caption / small dimensions). Returns the affected count.",
          "bodySchema": {
            "type": "object",
            "properties": {
              "action": {
                "type": "string",
                "enum": [
                  "approve_all",
                  "delete_low_quality"
                ]
              }
            },
            "required": [
              "action"
            ],
            "additionalProperties": false
          }
        },
        "listProjectMedia": {
          "name": "listProjectMedia",
          "path": "/projects/:id/media",
          "method": "GET",
          "description": "List the media catalog the agent can send (MediaAsset rows of the project's collection, deletedAt IS NULL), org-scoped + ownership. Each row's url is resolved ON-READ: externalUrl used directly (pricing), else storageKey signed (BUCKETS.MEDIA) — fail-safe: a failed signature yields url=null for that item and never drops the list. storageKey is never exposed. Project without KB ⇒ { media: [] }."
        },
        "patchMediaAsset": {
          "name": "patchMediaAsset",
          "path": "/media/:mediaId",
          "method": "PATCH",
          "description": "Curate a single media asset (exactly ONE action per call): set caption, soft-delete (deleted:true), or confirm/unconfirm (confirmed). Org-scoped via updateMany ({id, organizationId}); affected count 0 ⇒ 404 (not found / no access / other org).",
          "bodySchema": {
            "type": "object",
            "properties": {
              "caption": {
                "type": "string",
                "maxLength": 2000
              },
              "deleted": {
                "type": "boolean",
                "enum": [
                  true
                ]
              },
              "confirmed": {
                "type": "boolean"
              }
            },
            "additionalProperties": false
          }
        },
        "publish": {
          "name": "publish",
          "path": "/deploy/publish",
          "method": "POST",
          "description": "Orchestrates the full Builder deploy saga (publish version → create instance → attach connection).",
          "bodySchema": {
            "type": "object",
            "properties": {
              "projectId": {
                "type": "string",
                "format": "uuid"
              },
              "promptVersionId": {
                "type": "string",
                "format": "uuid"
              }
            },
            "required": [
              "projectId",
              "promptVersionId"
            ],
            "additionalProperties": false
          }
        },
        "publishVersion": {
          "name": "publishVersion",
          "path": "/deploy/publish-version",
          "method": "POST",
          "description": "Promove uma versão de prompt para produção (sem criar instância; o canal é anexado à parte).",
          "bodySchema": {
            "type": "object",
            "properties": {
              "projectId": {
                "type": "string",
                "format": "uuid"
              },
              "promptVersionId": {
                "type": "string",
                "format": "uuid"
              }
            },
            "required": [
              "projectId",
              "promptVersionId"
            ],
            "additionalProperties": false
          }
        },
        "status": {
          "name": "status",
          "path": "/calendar/status/:projectId",
          "method": "GET",
          "description": "Retorna o status da conexão do Google Calendar do projeto (status + calendarEmail), org-scoped."
        },
        "rollback": {
          "name": "rollback",
          "path": "/deploy/:deploymentId/rollback",
          "method": "POST",
          "description": "Compensação manual — reverte um BuilderDeployment.",
          "bodySchema": {
            "anyOf": [
              {
                "not": {}
              },
              {
                "type": "object",
                "properties": {},
                "additionalProperties": false
              }
            ]
          }
        },
        "save": {
          "name": "save",
          "path": "/channel/credentials",
          "method": "POST",
          "description": "Salva (cria/atualiza) credenciais Cloud API ou Instagram numa Connection, encriptando os tokens sensíveis.",
          "bodySchema": {
            "allOf": [
              {
                "anyOf": [
                  {
                    "type": "object",
                    "properties": {
                      "kind": {
                        "type": "string",
                        "enum": [
                          "whatsapp_business"
                        ]
                      },
                      "accessToken": {
                        "type": "string",
                        "minLength": 1
                      },
                      "phoneNumberId": {
                        "type": "string",
                        "minLength": 1
                      },
                      "wabaId": {
                        "type": "string",
                        "minLength": 1
                      },
                      "verifyToken": {
                        "type": "string",
                        "minLength": 1
                      },
                      "verifiedName": {
                        "type": "string",
                        "minLength": 1
                      }
                    },
                    "required": [
                      "kind",
                      "accessToken",
                      "phoneNumberId",
                      "wabaId",
                      "verifyToken"
                    ],
                    "additionalProperties": false
                  },
                  {
                    "type": "object",
                    "properties": {
                      "kind": {
                        "type": "string",
                        "enum": [
                          "whatsapp_cloud"
                        ]
                      },
                      "accessToken": {
                        "$ref": "#/allOf/0/anyOf/0/properties/accessToken"
                      },
                      "phoneNumberId": {
                        "$ref": "#/allOf/0/anyOf/0/properties/phoneNumberId"
                      },
                      "wabaId": {
                        "$ref": "#/allOf/0/anyOf/0/properties/wabaId"
                      },
                      "verifyToken": {
                        "$ref": "#/allOf/0/anyOf/0/properties/verifyToken"
                      },
                      "verifiedName": {
                        "$ref": "#/allOf/0/anyOf/0/properties/verifiedName"
                      }
                    },
                    "required": [
                      "kind",
                      "accessToken",
                      "phoneNumberId",
                      "wabaId",
                      "verifyToken"
                    ],
                    "additionalProperties": false
                  },
                  {
                    "type": "object",
                    "properties": {
                      "kind": {
                        "type": "string",
                        "enum": [
                          "instagram"
                        ]
                      },
                      "igAccountId": {
                        "type": "string",
                        "minLength": 1
                      },
                      "pageAccessToken": {
                        "type": "string",
                        "minLength": 1
                      },
                      "appSecret": {
                        "type": "string",
                        "minLength": 1
                      },
                      "verifyToken": {
                        "type": "string",
                        "minLength": 1
                      }
                    },
                    "required": [
                      "kind",
                      "igAccountId",
                      "pageAccessToken",
                      "appSecret",
                      "verifyToken"
                    ],
                    "additionalProperties": false
                  }
                ]
              },
              {
                "type": "object",
                "properties": {
                  "connectionId": {
                    "type": "string",
                    "format": "uuid"
                  },
                  "projectId": {
                    "type": "string",
                    "format": "uuid"
                  },
                  "name": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 120
                  }
                }
              }
            ]
          }
        },
        "getStatus": {
          "name": "getStatus",
          "path": "/channel/credentials/:connectionId",
          "method": "GET",
          "description": "Retorna o status de configuração das credenciais (configurado + last4), nunca o token cru."
        },
        "provisionWhatsApp": {
          "name": "provisionWhatsApp",
          "path": "/channel/provision-whatsapp",
          "method": "POST",
          "description": "Provisiona uma instância UAZAPI para o projeto (cria instância + webhook + Connection + QR) e anexa ao agente.",
          "bodySchema": {
            "type": "object",
            "properties": {
              "projectId": {
                "type": "string",
                "format": "uuid"
              }
            },
            "required": [
              "projectId"
            ],
            "additionalProperties": false
          }
        },
        "getIdentity": {
          "name": "getIdentity",
          "path": "/identity/:projectId",
          "method": "GET",
          "description": "Retorna o Card de Identidade do projeto (objetivo/persona/tom/disclosure)."
        },
        "updateIdentity": {
          "name": "updateIdentity",
          "path": "/identity/:projectId",
          "method": "PATCH",
          "description": "Atualiza (merge parcial) o Card de Identidade e sincroniza os campos estruturados do agente.",
          "bodySchema": {
            "type": "object",
            "properties": {
              "objetivo": {
                "type": "string",
                "maxLength": 200
              },
              "displayName": {
                "type": "string",
                "maxLength": 80
              },
              "persona": {
                "type": "string",
                "maxLength": 400
              },
              "tom": {
                "type": "string",
                "enum": [
                  "formal",
                  "amigavel",
                  "direto"
                ]
              },
              "usaEmojis": {
                "type": "boolean"
              },
              "disclosureMode": {
                "type": "string",
                "enum": [
                  "ai_explicit",
                  "human_passthrough",
                  "custom"
                ]
              },
              "disclosureCustomText": {
                "type": "string",
                "maxLength": 600
              },
              "avatarUrl": {
                "type": "string",
                "maxLength": 500
              }
            },
            "additionalProperties": false
          }
        },
        "connectLink": {
          "name": "connectLink",
          "path": "/calendar/connect-link",
          "method": "POST",
          "description": "Cria um link público de conexão do Google Calendar (CalendarConnection PENDING, token de 7 dias) e retorna o shareLink.",
          "bodySchema": {
            "type": "object",
            "properties": {
              "projectId": {
                "type": "string",
                "format": "uuid"
              }
            },
            "additionalProperties": false
          }
        },
        "disconnect": {
          "name": "disconnect",
          "path": "/calendar/:projectId",
          "method": "DELETE",
          "description": "Desconecta o Google Calendar do projeto: marca CalendarConnection como REVOKED e remove o OrganizationProvider google-calendar.",
          "bodySchema": {
            "anyOf": [
              {
                "not": {}
              },
              {
                "type": "object",
                "properties": {},
                "additionalProperties": false
              }
            ]
          }
        },
        "eventsPreview": {
          "name": "eventsPreview",
          "path": "/calendar/events-preview/:projectId",
          "method": "GET",
          "description": "Conta os compromissos (intervalos ocupados via freeBusy) das próximas ~3 semanas da agenda conectada ao projeto, para a prova social do card calendar_connect. Org-scoped. Degrada para available:false sem nunca dar 500."
        },
        "getKnowledge": {
          "name": "getKnowledge",
          "path": "/knowledge/:projectId",
          "method": "GET",
          "description": "Retorna a coleção RAG do projeto, suas fontes e o status (useRAG)."
        },
        "ensureCollection": {
          "name": "ensureCollection",
          "path": "/knowledge/:projectId/collection",
          "method": "POST",
          "description": "Cria (idempotente) a coleção RAG do projeto e a vincula ao agente.",
          "bodySchema": {
            "type": "object",
            "properties": {
              "description": {
                "type": "string",
                "maxLength": 400
              }
            },
            "additionalProperties": false
          }
        },
        "toggleRAG": {
          "name": "toggleRAG",
          "path": "/knowledge/:projectId",
          "method": "PATCH",
          "description": "Liga/desliga o uso da base de conhecimento pelo agente (useRAG).",
          "bodySchema": {
            "type": "object",
            "properties": {
              "enabled": {
                "type": "boolean"
              }
            },
            "required": [
              "enabled"
            ],
            "additionalProperties": false
          }
        },
        "addUrlSource": {
          "name": "addUrlSource",
          "path": "/knowledge/:projectId/source/url",
          "method": "POST",
          "description": "Adiciona uma URL à base e dispara a ingestão (extrai, chunk, embeda).",
          "bodySchema": {
            "type": "object",
            "properties": {
              "url": {
                "type": "string",
                "format": "uri"
              }
            },
            "required": [
              "url"
            ],
            "additionalProperties": false
          }
        },
        "addTextSource": {
          "name": "addTextSource",
          "path": "/knowledge/:projectId/source/text",
          "method": "POST",
          "description": "Adiciona um texto colado à base e dispara a ingestão.",
          "bodySchema": {
            "type": "object",
            "properties": {
              "title": {
                "type": "string",
                "maxLength": 160
              },
              "text": {
                "type": "string",
                "minLength": 1,
                "maxLength": 200000
              }
            },
            "required": [
              "text"
            ],
            "additionalProperties": false
          }
        },
        "deleteSource": {
          "name": "deleteSource",
          "path": "/knowledge/:projectId/source/:sourceId",
          "method": "DELETE",
          "description": "Remove uma fonte da base (chunks são apagados em cascade)."
        },
        "getPricing": {
          "name": "getPricing",
          "path": "/pricing/:projectId",
          "method": "GET",
          "description": "Lista o catálogo de preços do projeto e seus itens."
        },
        "ensureList": {
          "name": "ensureList",
          "path": "/pricing/:projectId/list",
          "method": "POST",
          "description": "Cria (idempotente) a lista de preços do projeto e a vincula ao agente.",
          "bodySchema": {
            "anyOf": [
              {
                "not": {}
              },
              {
                "type": "object",
                "properties": {},
                "additionalProperties": false
              }
            ]
          }
        },
        "addItem": {
          "name": "addItem",
          "path": "/pricing/:projectId/item",
          "method": "POST",
          "description": "Adiciona um item ao catálogo (price em reais, convertido p/ centavos).",
          "bodySchema": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "minLength": 1,
                "maxLength": 160
              },
              "price": {
                "type": "number",
                "minimum": 0
              },
              "description": {
                "type": "string",
                "maxLength": 500
              },
              "category": {
                "type": "string",
                "maxLength": 80
              },
              "aliases": {
                "type": "array",
                "items": {
                  "type": "string",
                  "maxLength": 80
                },
                "maxItems": 20
              }
            },
            "required": [
              "name",
              "price"
            ],
            "additionalProperties": false
          }
        },
        "deleteItem": {
          "name": "deleteItem",
          "path": "/pricing/:projectId/item/:itemId",
          "method": "DELETE",
          "description": "Remove um item do catálogo (valida org)."
        },
        "updateCredential": {
          "name": "updateCredential",
          "path": "/credential/:projectId",
          "method": "PATCH",
          "description": "Vincula (ou limpa) a chave BYOK que o agente do projeto deve usar (AIAgentConfig.organizationProviderId).",
          "bodySchema": {
            "type": "object",
            "properties": {
              "organizationProviderId": {
                "type": "string",
                "minLength": 1,
                "nullable": true
              }
            },
            "required": [
              "organizationProviderId"
            ],
            "additionalProperties": false
          }
        }
      }
    },
    "device-sessions": {
      "name": "deviceSessions",
      "path": "/device-sessions",
      "description": "Device session listing and revocation",
      "actions": {
        "list": {
          "name": "list",
          "path": "/",
          "method": "GET",
          "description": "List non-revoked device sessions ordered by last activity"
        },
        "revoke": {
          "name": "revoke",
          "path": "/revoke",
          "method": "POST",
          "description": "Revoke a specific device session (IDOR-guarded)",
          "bodySchema": {
            "type": "object",
            "properties": {
              "deviceSessionId": {
                "type": "string",
                "minLength": 1
              }
            },
            "required": [
              "deviceSessionId"
            ],
            "additionalProperties": false
          }
        },
        "revokeAll": {
          "name": "revokeAll",
          "path": "/revoke-all",
          "method": "POST",
          "description": "Revoke all active device sessions, optionally preserving the current device",
          "bodySchema": {
            "type": "object",
            "properties": {
              "currentDeviceSessionId": {
                "type": "string",
                "minLength": 1
              }
            },
            "additionalProperties": false
          }
        }
      }
    },
    "logs": {
      "name": "logs",
      "path": "/logs",
      "description": "Log management and AI analysis (admin only)",
      "actions": {
        "list": {
          "name": "list",
          "path": "/",
          "method": "GET",
          "description": "List logs with filters",
          "querySchema": {
            "anyOf": [
              {
                "not": {}
              },
              {
                "type": "object",
                "properties": {
                  "level": {
                    "type": "string",
                    "enum": [
                      "DEBUG",
                      "INFO",
                      "WARN",
                      "ERROR",
                      "CRITICAL"
                    ]
                  },
                  "source": {
                    "type": "string"
                  },
                  "userId": {
                    "type": "string"
                  },
                  "organizationId": {
                    "type": "string"
                  },
                  "search": {
                    "type": "string"
                  },
                  "startDate": {
                    "type": "string"
                  },
                  "endDate": {
                    "type": "string"
                  },
                  "limit": {
                    "type": "number",
                    "minimum": 1,
                    "maximum": 500,
                    "default": 100
                  },
                  "offset": {
                    "type": "number",
                    "minimum": 0,
                    "default": 0
                  }
                },
                "additionalProperties": false
              }
            ]
          }
        },
        "stats": {
          "name": "stats",
          "path": "/stats",
          "method": "GET",
          "description": "Get log statistics",
          "querySchema": {
            "anyOf": [
              {
                "not": {}
              },
              {
                "type": "object",
                "properties": {
                  "period": {
                    "type": "string",
                    "enum": [
                      "hour",
                      "day",
                      "week"
                    ],
                    "default": "day"
                  }
                },
                "additionalProperties": false
              }
            ]
          }
        },
        "sources": {
          "name": "sources",
          "path": "/sources",
          "method": "GET",
          "description": "Get list of log sources"
        },
        "analyze": {
          "name": "analyze",
          "path": "/analyze",
          "method": "POST",
          "description": "Analyze logs using AI",
          "bodySchema": {
            "anyOf": [
              {
                "not": {}
              },
              {
                "type": "object",
                "properties": {
                  "startDate": {
                    "type": "string"
                  },
                  "endDate": {
                    "type": "string"
                  },
                  "source": {
                    "type": "string"
                  },
                  "level": {
                    "type": "string",
                    "enum": [
                      "DEBUG",
                      "INFO",
                      "WARN",
                      "ERROR",
                      "CRITICAL"
                    ]
                  },
                  "limit": {
                    "type": "number",
                    "minimum": 1,
                    "maximum": 1000,
                    "default": 500
                  }
                },
                "additionalProperties": false
              }
            ]
          }
        },
        "analyzeError": {
          "name": "analyzeError",
          "path": "/analyze/:id",
          "method": "POST",
          "description": "AI analysis of a specific error"
        },
        "recentAnalyses": {
          "name": "recentAnalyses",
          "path": "/analyses",
          "method": "GET",
          "description": "Get recent AI analyses",
          "querySchema": {
            "anyOf": [
              {
                "not": {}
              },
              {
                "type": "object",
                "properties": {
                  "limit": {
                    "type": "number",
                    "minimum": 1,
                    "maximum": 50,
                    "default": 10
                  }
                },
                "additionalProperties": false
              }
            ]
          }
        },
        "create": {
          "name": "create",
          "path": "/",
          "method": "POST",
          "description": "Create a log entry manually",
          "bodySchema": {
            "type": "object",
            "properties": {
              "level": {
                "type": "string",
                "enum": [
                  "DEBUG",
                  "INFO",
                  "WARN",
                  "ERROR",
                  "CRITICAL"
                ]
              },
              "message": {
                "type": "string",
                "minLength": 1
              },
              "source": {
                "type": "string",
                "minLength": 1
              },
              "action": {
                "type": "string"
              },
              "details": {
                "type": "string"
              },
              "metadata": {
                "type": "object",
                "additionalProperties": {}
              },
              "tags": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "level",
              "message",
              "source"
            ],
            "additionalProperties": false
          }
        }
      }
    },
    "logs-sse": {
      "name": "logsSSE",
      "path": "/logs",
      "description": "Real-time log streaming via SSE",
      "actions": {
        "stream": {
          "name": "stream",
          "path": "/stream",
          "method": "GET",
          "description": "Stream logs in real-time via SSE"
        }
      }
    },
    "messages": {
      "name": "messages",
      "path": "/messages",
      "description": "Chat messages and sessions (multi-tenant, org-isolated)",
      "actions": {
        "list": {
          "name": "list",
          "path": "/",
          "method": "GET",
          "description": "Lista mensagens de uma sessão de chat, filtradas pela organization do usuário.",
          "querySchema": {
            "anyOf": [
              {
                "not": {}
              },
              {
                "type": "object",
                "properties": {
                  "sessionId": {
                    "type": "string",
                    "minLength": 1
                  },
                  "limit": {
                    "type": "number",
                    "minimum": 1,
                    "maximum": 100,
                    "default": 50
                  },
                  "offset": {
                    "type": "number",
                    "minimum": 0,
                    "default": 0
                  }
                },
                "required": [
                  "sessionId"
                ],
                "additionalProperties": false
              }
            ]
          }
        },
        "getById": {
          "name": "getById",
          "path": "/:id",
          "method": "GET",
          "description": "Retorna uma mensagem pelo ID, isolada pela organization do usuário."
        },
        "listSessions": {
          "name": "listSessions",
          "path": "/sessions",
          "method": "GET",
          "description": "Lista sessões de chat da organization do usuário, com filtro opcional de status.",
          "querySchema": {
            "anyOf": [
              {
                "not": {}
              },
              {
                "type": "object",
                "properties": {
                  "status": {
                    "type": "string"
                  },
                  "limit": {
                    "type": "number",
                    "minimum": 1,
                    "maximum": 100,
                    "default": 50
                  },
                  "offset": {
                    "type": "number",
                    "minimum": 0,
                    "default": 0
                  }
                },
                "additionalProperties": false
              }
            ]
          }
        }
      }
    },
    "departments": {
      "name": "departments",
      "path": "/departments",
      "description": "Departamentos e membros da roleta (round-robin) — multi-tenant, org-isolated",
      "actions": {
        "list": {
          "name": "list",
          "path": "/",
          "method": "GET",
          "description": "Lista departamentos da organização ativa (filtros opcionais por type/isActive).",
          "querySchema": {
            "anyOf": [
              {
                "not": {}
              },
              {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "support",
                      "sales",
                      "custom"
                    ]
                  },
                  "isActive": {
                    "type": "boolean"
                  },
                  "limit": {
                    "type": "number",
                    "minimum": 1,
                    "maximum": 100,
                    "default": 50
                  },
                  "offset": {
                    "type": "number",
                    "minimum": 0,
                    "default": 0
                  }
                },
                "additionalProperties": false
              }
            ]
          }
        },
        "create": {
          "name": "create",
          "path": "/",
          "method": "POST",
          "description": "Cria um departamento na organização ativa (slug único por org).",
          "bodySchema": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "minLength": 2,
                "maxLength": 120
              },
              "slug": {
                "type": "string",
                "minLength": 2,
                "maxLength": 60,
                "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
              },
              "description": {
                "type": "string",
                "maxLength": 500
              },
              "type": {
                "type": "string",
                "enum": [
                  "support",
                  "sales",
                  "custom"
                ],
                "default": "support"
              },
              "isActive": {
                "type": "boolean",
                "default": true
              }
            },
            "required": [
              "name",
              "slug"
            ],
            "additionalProperties": false
          }
        },
        "listMembers": {
          "name": "listMembers",
          "path": "/:id/members",
          "method": "GET",
          "description": "Lista os membros (atendentes) de um departamento, na ordem da roleta (position asc)."
        },
        "addMember": {
          "name": "addMember",
          "path": "/:id/members",
          "method": "POST",
          "description": "Adiciona (ou atualiza position/isActive de) um atendente na roleta do departamento.",
          "bodySchema": {
            "type": "object",
            "properties": {
              "userId": {
                "type": "string",
                "format": "uuid"
              },
              "position": {
                "type": "integer",
                "minimum": 0,
                "default": 0
              },
              "isActive": {
                "type": "boolean",
                "default": true
              }
            },
            "required": [
              "userId"
            ],
            "additionalProperties": false
          }
        },
        "removeMember": {
          "name": "removeMember",
          "path": "/:id/members/:userId",
          "method": "DELETE",
          "description": "Remove um atendente da roleta do departamento."
        }
      }
    },
    "providers": {
      "name": "providers",
      "path": "/providers",
      "description": "BYOK — org-level AI provider key management",
      "actions": {
        "listProviders": {
          "name": "listProviders",
          "path": "/",
          "method": "GET",
          "description": "Return BYOK configuration status for all supported AI providers"
        },
        "upsertProvider": {
          "name": "upsertProvider",
          "path": "/:provider",
          "method": "PATCH",
          "description": "Store (or replace) an API key for the given AI provider",
          "bodySchema": {
            "type": "object",
            "properties": {
              "apiKey": {
                "type": "string",
                "minLength": 16,
                "maxLength": 512
              },
              "config": {
                "type": "object",
                "additionalProperties": {}
              }
            },
            "required": [
              "apiKey"
            ],
            "additionalProperties": false
          }
        },
        "deleteProvider": {
          "name": "deleteProvider",
          "path": "/:provider",
          "method": "DELETE",
          "description": "Remove a stored API key so the org falls back to the env-level key"
        },
        "listProviderKeys": {
          "name": "listProviderKeys",
          "path": "/:provider/keys",
          "method": "GET",
          "description": "Lista todas as chaves BYOK (rotuladas) de um provider para a org"
        },
        "createProviderKey": {
          "name": "createProviderKey",
          "path": "/:provider/keys",
          "method": "POST",
          "description": "Cria uma nova chave BYOK rotulada para o provider (múltiplas chaves)",
          "bodySchema": {
            "type": "object",
            "properties": {
              "apiKey": {
                "type": "string",
                "minLength": 8
              },
              "name": {
                "type": "string",
                "minLength": 1,
                "maxLength": 60
              }
            },
            "required": [
              "apiKey",
              "name"
            ],
            "additionalProperties": false
          }
        },
        "deleteProviderKey": {
          "name": "deleteProviderKey",
          "path": "/keys/:id",
          "method": "DELETE",
          "description": "Remove uma chave BYOK específica por id (org-scoped)"
        }
      }
    }
  },
  "docs": {}
} as const

export type AppRouterSchemaType = typeof AppRouterSchema
