/**
 * Generated by @igniter-js/cli
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY
 *
 * Generated: 2025-10-12T16:48:59.443Z
 * Framework: nextjs
 * Output: src
 */

import { createIgniterClient, useIgniterQueryClient } from '@igniter-js/core/client'
import type { AppRouterType } from './igniter.router'

/**
 * Type-safe API client generated from your Igniter router
 *
 * Usage in Server Components:
 * const users = await api.users.list.query()
 *
 * Usage in Client Components:
 * const { data } = api.users.list.useQuery()
 */
export const api = createIgniterClient<AppRouterType>({
  baseURL: process.env.NEXT_PUBLIC_IGNITER_API_URL || 'http://localhost:3000',
  basePATH: process.env.NEXT_PUBLIC_IGNITER_API_BASE_PATH || '/api/v1',
  router: () => {
    if (typeof window === 'undefined') {
      // Server-side: try to load the full router (for Server Components that use
      // api.*.query() with direct DB access). If the router fails to initialize
      // (e.g. during build when Redis/BullMQ are unavailable), fall back to a
      // router-shaped stub so SSR pre-rendering of "use client" pages doesn't crash.
      try {
        const router = require('./igniter.router').AppRouter
        if (router) return router
      } catch {
        // ignore – fall through to stub
      }
      // Build a deep Proxy stub so any api.controller.action.useQuery/useMutation call
      // returns safe no-op defaults during SSR prerendering (when Redis/BullMQ are unavailable).
      const noopResult = { data: undefined, isLoading: true, error: null, refetch: () => {} }
      const mutationResult = { mutate: () => {}, mutateAsync: async () => ({}), isPending: false, error: null }
      const makeActionStub = (): any => {
        const fn: any = () => noopResult
        fn.useQuery = () => noopResult
        fn.useMutation = () => mutationResult
        fn.query = () => noopResult
        fn.mutate = () => noopResult
        return new Proxy(fn, {
          get(target: any, prop: string) {
            if (prop in target) return target[prop]
            return makeActionStub()
          },
        })
      }
      const callerStub = new Proxy({} as Record<string, unknown>, {
        get(_target, _ctrl) {
          return new Proxy({} as Record<string, unknown>, {
            get(_t, _action) {
              return makeActionStub()
            },
          })
        },
      })
      return { caller: callerStub }
    }

    // Client-side: use schema for type-safe API calls
    return require('./igniter.schema').AppRouterSchema
  },
})

export { useIgniterQueryClient }

/**
 * Get authentication token.
 * With httpOnly cookies, the token is sent automatically by the browser.
 * This function is kept for backward compatibility but returns null
 * since tokens are no longer stored in localStorage.
 *
 * @deprecated Tokens are now managed via httpOnly cookies set by the backend.
 */
export function getAuthToken(): string | null {
  return null
}

/**
 * Get authentication headers for API calls.
 * With httpOnly cookies, credentials are sent automatically.
 * This function is kept for backward compatibility.
 *
 * @deprecated Tokens are now managed via httpOnly cookies set by the backend.
 */
export function getAuthHeaders(): Record<string, string> {
  return {}
}
