name: PR Welcome Comment

on:
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Add welcome comment
        uses: actions/github-script@v7
        with:
          script: |
            const body = `👋 Bem-vindo(a) ao PR!

            Obrigado por contribuir com o App Quayer. Nosso CI irá rodar lint, typecheck e testes.

            Dicas:
            - Use Conventional Commits (feat:, fix:, chore:, docs:, refactor:, perf:, test:)
            - Verifique se não há segredos/credenciais no PR
            - Consulte o CONTRIBUTING.md para boas práticas

            Bons commits! 🚀`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });


